config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  devise_for :users
  resources :projects do
    resources :accesses, only: [:new, :destroy]
  end

end

app/models/access.rb
class Access < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :procats
  has_many :projects, through: :procats
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/procat.rb
class Procat < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :procats
  has_many :categories, through: :procats

  has_many :accesses
  has_many :users, through: :accesses

  belongs_to :owner, class_name: 'User',
                    foreign_key: 'owner_id'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accesses
  has_many :projects, through: :accesses

  has_many :owner, class_name: 'User' 

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_project
  def new
    @accesses = Access.new
    @accesses.user = current_user
    @accesses.project = @project
    @accesses.save
    redirect_to project_path(@project)
  end

  def destroy
    @accesses = Project.find(params[:project_id]).accesses
    @accesses.destroy
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  #def after_sign_in_path_for(resources)
  #  dashboards_path
  #end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :own_auth, only: [:edit, :update,:destroy ]
  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, {category_ids: []} )
    end

    def own_auth
      if current_user != Project.find(params[:id]).owner
        redirect_to @project
      end
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def markdownify(content)
    pipeline_context = { gfm: true, asset_root: '/public/images'}
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::EmojiFilter,
      HTML::Pipeline::SanitizationFilter,
    ], pipeline_context
    pipeline.call(content)[:output].to_s.html_safe
  end
end

app/views/accesses/destroy.html.erb
<h1>Accesses#destroy</h1>
<p>Find me in app/views/accesses/destroy.html.erb</p>

app/views/accesses/new.html.erb
<h1>Accesses#new</h1>
<p>Find me in app/views/accesses/new.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Work3" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Work3" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name %>

    <%= f.input :description, as: :text %>

    <%= f.association :categories,  label_method: :name, value_method: :id, include_blank: false  %>

    <%= f.button :submit %>

  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= markdownify project.description %></td>
        <td><% project.categories.each do |pc| %>
            <%= pc.name %>
          <% end %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdownify @project.description %>
</p>

<ul>
<% @project.users.each do |p| %>
  <li>
    <%= p.email %>
  </li>
<% end %>
</ul>
<br>
  <%= link_to 'Collaborate', new_project_access_path(@project)%>
<br>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>